import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = resolve(__dirname, "..");

// ─── Font variants ────────────────────────────────────────────────────────────
// Each category gets its own font file so the Dirham symbol adapts to the
// surrounding typeface category.
// Replace the SVG in each src/svg-<variant>/ directory with a custom design.
const VARIANTS = [
	{ name: "dirham", svgDir: "svg", fontDir: "fonts" }, // default
	{ name: "dirham-sans", svgDir: "svg-sans", fontDir: "fonts/sans" },
	{ name: "dirham-serif", svgDir: "svg-serif", fontDir: "fonts/serif" },
	{ name: "dirham-mono", svgDir: "svg-mono", fontDir: "fonts/mono" },
	{ name: "dirham-arabic", svgDir: "svg-arabic", fontDir: "fonts/arabic" },
];

async function buildVariant(svgtofont, variant) {
	const fontDist = resolve(rootDir, "dist", variant.fontDir);
	mkdirSync(fontDist, { recursive: true });

	await svgtofont({
		src: resolve(rootDir, "src", variant.svgDir),
		dist: fontDist,
		fontName: variant.name,
		css: false,
		startUnicode: 0x20c3,
		useNameAsUnicode: false,
		svgicons2svgfont: {
			fontHeight: 1000,
			normalize: true,
			centerHorizontally: true,
			descent: 100,
		},
		outSVGReact: false,
		outSVGPath: false,
		generateInfoData: true,
		website: undefined,
	});

	// Clean up unnecessary files generated by svgtofont
	const extras = [
		`${variant.name}.css`,
		`${variant.name}.less`,
		`${variant.name}.module.less`,
		`${variant.name}.styl`,
		`${variant.name}.svg`,
		`${variant.name}.symbol.svg`,
		`${variant.name}.eot`,
	];
	for (const file of extras) {
		const fp = resolve(fontDist, file);
		if (existsSync(fp)) unlinkSync(fp);
	}

	console.log(`  ✓ ${variant.name} → dist/${variant.fontDir}/`);
}

// ─── CSS / SCSS generation ────────────────────────────────────────────────────

function fontFaceCSS(name, path) {
	return `@font-face {
  font-family: "${name}";
  src:
    url("${path}.woff2") format("woff2"),
    url("${path}.woff") format("woff"),
    url("${path}.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
  font-display: swap;
  unicode-range: U+20C3;
}`;
}

function generateCSS() {
	return `/* dirham - UAE Dirham currency symbol font
 * Provides category-specific variants so U+20C3 adapts to surrounding typography.
 * Use font-family: "YourFont", "Dirham-Sans" (or -Serif / -Mono / -Arabic);
 * The browser falls back to the matching Dirham variant for U+20C3.
 */

/* ── Default (standalone use) ────────────────────────────────────────────── */
${fontFaceCSS("Dirham", "../fonts/dirham")}

/* ── Category variants ───────────────────────────────────────────────────── */
${fontFaceCSS("Dirham-Sans", "../fonts/sans/dirham-sans")}

${fontFaceCSS("Dirham-Serif", "../fonts/serif/dirham-serif")}

${fontFaceCSS("Dirham-Mono", "../fonts/mono/dirham-mono")}

${fontFaceCSS("Dirham-Arabic", "../fonts/arabic/dirham-arabic")}

/* ── Base class (uses default Dirham) ────────────────────────────────────── */
.dirham-symbol {
  font-family: "Dirham" !important;
  speak: never;
  font-style: normal;
  font-weight: inherit;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.dirham-symbol::before {
  content: "\\20C3";
}

/* ── Category class modifiers ────────────────────────────────────────────── */
.dirham-symbol-sans  { font-family: "Dirham-Sans"   !important; }
.dirham-symbol-serif { font-family: "Dirham-Serif"  !important; }
.dirham-symbol-mono  { font-family: "Dirham-Mono"   !important; }
.dirham-symbol-arabic{ font-family: "Dirham-Arabic" !important; }

.dirham-symbol-sans::before,
.dirham-symbol-serif::before,
.dirham-symbol-mono::before,
.dirham-symbol-arabic::before {
  content: "\\20C3";
}

/* Screen reader only — use alongside .dirham-symbol for accessibility */
.dirham-sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}
`;
}

function generateSCSS() {
	return `// dirham - UAE Dirham currency symbol font (multi-variant)
$dirham-font-path: "../fonts" !default;
$dirham-unicode: "\\20C3" !default;

// ── Default ─────────────────────────────────────────────────────────────────
@font-face {
  font-family: "Dirham";
  src:
    url("#{$dirham-font-path}/dirham.woff2") format("woff2"),
    url("#{$dirham-font-path}/dirham.woff") format("woff"),
    url("#{$dirham-font-path}/dirham.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
  font-display: swap;
  unicode-range: U+20C3;
}

// ── Category variants ───────────────────────────────────────────────────────
@each $variant in sans, serif, mono, arabic {
  @font-face {
    font-family: "Dirham-#{$variant}";
    src:
      url("#{$dirham-font-path}/#{$variant}/dirham-#{$variant}.woff2") format("woff2"),
      url("#{$dirham-font-path}/#{$variant}/dirham-#{$variant}.woff") format("woff"),
      url("#{$dirham-font-path}/#{$variant}/dirham-#{$variant}.ttf") format("truetype");
    font-weight: normal;
    font-style: normal;
    font-display: swap;
    unicode-range: U+20C3;
  }
}

// ── Base class ──────────────────────────────────────────────────────────────
.dirham-symbol {
  font-family: "Dirham" !important;
  speak: never;
  font-style: normal;
  font-weight: inherit;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;

  &::before {
    content: $dirham-unicode;
  }
}

// ── Category modifiers ──────────────────────────────────────────────────────
@each $variant in sans, serif, mono, arabic {
  .dirham-symbol-#{$variant} {
    font-family: "Dirham-#{$variant}" !important;
    &::before { content: $dirham-unicode; }
  }
}

.dirham-sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}
`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function buildFont() {
	const svgtofont = (await import("svgtofont")).default;
	const cssDist = resolve(rootDir, "dist", "css");
	mkdirSync(cssDist, { recursive: true });

	console.log("Building font variants…");
	for (const variant of VARIANTS) {
		await buildVariant(svgtofont, variant);
	}

	writeFileSync(resolve(cssDist, "dirham.css"), generateCSS(), "utf-8");
	writeFileSync(resolve(cssDist, "dirham.scss"), generateSCSS(), "utf-8");
	console.log("  ✓ CSS/SCSS generated in dist/css/");
	console.log("Done — 5 font variants built.");
}

buildFont().catch((err) => {
	console.error("Font build failed:", err);
	process.exit(1);
});
